/*
* @Author: Benjamin Marquardt
* @Date:   2017-01-26 13:19:23
* @Last Modified by:   Benjamin Marquardt
* @Last Modified time: 2017-01-30
*/
#define CHUNK_SIDE_SIZE		4
#define MAP_BUFFER_WIDTH 	64
#define MAP_BUFFER_HEIGHT	32
#define MAP_BUFFER_DEPTH 	16

typedef enum DIRECTION
{
	NORTH, NORTHWEST, WEST, SOUTHWEST,
	SOUTH, SOUTHEAST, EAST, NORTHEAST,
	UP, DOWN
} DIRECTION;

typedef enum CLIMBABLE_OBJECTS
{
	SHALLOWSTAIRS, STEEPSTAIRS, LADDER, 
	RAMP, ROPE, VERTICALCLIMB
} CLIMBABLE_OBJECTS;

typedef enum MATERIAL
{
	EMPTY, DIRT, SAND, PEBBLES, ROCK, GRASS, 
	SNOW, SALTWATER, FRESHWATER, ASPHALT, GRAVEL, 
	DIRTROAD, DIRTPATH, TARMAC, TURF, SMOOTHSTONE, 
	HARDWOOD, BRICK, COBBLESTONE, MARBLE, CARPET,
	LINOLEUM

} GROUND_MATERIAL;

typedef struct POS_PROPERTIES
{
	MATERIAL mat;
	void * OBJECTS[16];
	bool EMPTY;
	bool WALKABLE;
	bool SKY;
} POS_PROPERTIES;

typedef struct POS
{
	float X;
	float Y;
	float Z;
	POS_PROPERTIES *PROPS;
} POS;

typedef struct MAP_BUFFER
{
	POS GRID[CHUNK_SIDE_SIZE * MAP_BUFFER_WIDTH]
			[CHUNK_SIDE_SIZE * MAP_BUFFER_HEIGHT]
			[CHUNK_SIDE_SIZE * MAP_BUFFER_DEPTH];
} MAP_BUFFER;

typedef struct MAP_PROPERTIES
{
	POS *X_ORIGIN;
	POS *Y_ORIGIN;
	POS *Z_ORIGIN;
} MAP_PROPS;

void MoveMapFocus(DIRECTION);