/*
* @Author: Benjamin Marquardt
* @Date:   2017-01-26 13:19:23
* @Last Modified by:   Benjamin Marquardt
* @Last Modified time: 2017-01-30
*/
#define CHUNK_SIDE_SIZE		4
#define MAP_BUFFER_WIDTH 	64
#define MAP_BUFFER_HEIGHT	32
#define MAP_BUFFER_DEPTH 	16
#define WORLD_SEED 			3158582976

typedef enum DIRECTION
{
	NORTH, NORTHWEST, WEST, SOUTHWEST,
	SOUTH, SOUTHEAST, EAST, NORTHEAST,
	UP, DOWN
} DIRECTION;

typedef enum CLIMBABLE_OBJECTS
{
	SHALLOWSTAIRS, STEEPSTAIRS, LADDER,
	RAMP, ROPE, VERTICALCLIMB
} CLIMBABLE_OBJECTS;

typedef enum MATERIAL
{
	EMPTY, DIRT, SAND, PEBBLES, ROCK, GRASS,
	SNOW, SALTWATER, FRESHWATER, ASPHALT, GRAVEL,
	DIRTROAD, DIRTPATH, TARMAC, TURF, SMOOTHSTONE,
	HARDWOOD, BRICK, COBBLESTONE, MARBLE, CARPET,
	LINOLEUM

} GROUND_MATERIAL;

typedef enum OBJECT_FLAGS
{
	APPLE		= 1 << 0,
	ORANGE		= 1 << 1
} OBJECT_FLAGS;

typedef enum EQUIPPABLE_OBJECTS
{
	SWORD 			= 1 << 0,
	LAMP  			= 1 << 1,
	CLOTHES_MEAGER	= 1 << 2,
	CLOTHES_FINE 	= 1 << 3,
	ARMOR_MEAGER	= 1 << 4,
	ARMOR_FINE		= 1 << 5
} EQUIPPABLE_OBJECTS;

typedef struct POS_PROPERTIES
{
	MATERIAL MATERIAL;
	void * OBJECTS[16];
	bool EMPTY;
	bool WALKABLE;
	bool SKY;
} POS_PROPERTIES;

typedef struct POS
{
	float X;
	float Y;
	float Z;
	POS_PROPERTIES *PROPS;
} POS;

typedef struct MAP_BUFFER
{
	POS GRID[CHUNK_SIDE_SIZE * MAP_BUFFER_WIDTH]
			[CHUNK_SIDE_SIZE * MAP_BUFFER_HEIGHT]
			[CHUNK_SIDE_SIZE * MAP_BUFFER_DEPTH];
} MAP_BUFFER;

typedef struct MAP_PROPERTIES
{
	POS *X_ORIGIN;
	POS *Y_ORIGIN;
	POS *Z_ORIGIN;
} MAP_PROPS;

typedef struct ENTITY_PROPERTIES
{
	POS *P_EDGE[8]; // NW, N, NE, W, E, SW, S, SE
	POS *P;
	unsigned int OBJECTS;
	unsigned int EQUIPPED;
	int STATUS;
	float HEALTH;
	float X_POSITION;
	float Y_POSITION;
	float Z_POSITION;
} PLAYER_PROPERTIES;

void MoveMapFocus(DIRECTION);